project:
  type: book
  output-dir: docs

execute:
  echo: true
  warning: false
  message: false

book:
  title: "2025 NFLPA Data Analysis Competition"
  author:
    - Max Camateros-Mann
    - Kyle Coletta
    - Michael Falbo
    
  repo-url: https://github.com/colettak16/NFLPA-Data-Analysis
  date: today
  page-footer:
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - data.qmd
    - results.qmd
    - conclusion.qmd

format:
  html:
    theme: cosmo
    code-fold: true


